# Generated by Django 4.0.1 on 2023-10-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MATERIAL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='time',
        ),
    ]
